### ISSUE TITLE
[BUG] UI Toolkit `:active` does not work

### ISSUE THREAD

**Issue by xiaohai-huang** [ReactUnity/core#97]
## How to reproduce

```scss
.backButton {
    margin: 0;
    border: none;

    &:hover {
      background-color: red;
    }
    &:active {
      background-color: yellow;
    }
  }
```

The button's background does not turn yellow when it is in active state.

https://github.com/ReactUnity/core/assets/56380096/b2887d34-36e0-426b-a8a8-6e1033705bb9
